
package org.example.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClusterVmWebService", targetNamespace = "http://service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClusterVmWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.example.service.ClusterVm>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClusterVms", targetNamespace = "http://service.example.org/", className = "org.example.service.GetClusterVms")
    @ResponseWrapper(localName = "getClusterVmsResponse", targetNamespace = "http://service.example.org/", className = "org.example.service.GetClusterVmsResponse")
    @Action(input = "http://service.example.org/ClusterVmWebService/getClusterVmsRequest", output = "http://service.example.org/ClusterVmWebService/getClusterVmsResponse")
    public List<ClusterVm> getClusterVms(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Filter> arg0);

}
