
package org.example.standalone.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ValidationError", targetNamespace = "http://service.standalone.example.org/")
public class ValidationError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ValidationErrorFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ValidationError(String message, ValidationErrorFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ValidationError(String message, ValidationErrorFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.example.standalone.service.ValidationErrorFault
     */
    public ValidationErrorFault getFaultInfo() {
        return faultInfo;
    }

}
