
package org.example.standalone.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClusterVmService", targetNamespace = "http://service.standalone.example.org/", wsdlLocation = "http://localhost:9000/ClusterVmService?wsdl")
public class ClusterVmService
    extends Service
{

    private final static URL CLUSTERVMSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLUSTERVMSERVICE_EXCEPTION;
    private final static QName CLUSTERVMSERVICE_QNAME = new QName("http://service.standalone.example.org/", "ClusterVmService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/ClusterVmService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLUSTERVMSERVICE_WSDL_LOCATION = url;
        CLUSTERVMSERVICE_EXCEPTION = e;
    }

    public ClusterVmService() {
        super(__getWsdlLocation(), CLUSTERVMSERVICE_QNAME);
    }

    public ClusterVmService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLUSTERVMSERVICE_QNAME, features);
    }

    public ClusterVmService(URL wsdlLocation) {
        super(wsdlLocation, CLUSTERVMSERVICE_QNAME);
    }

    public ClusterVmService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLUSTERVMSERVICE_QNAME, features);
    }

    public ClusterVmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClusterVmService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClusterVmWebService
     */
    @WebEndpoint(name = "ClusterVmWebServicePort")
    public ClusterVmWebService getClusterVmWebServicePort() {
        return super.getPort(new QName("http://service.standalone.example.org/", "ClusterVmWebServicePort"), ClusterVmWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClusterVmWebService
     */
    @WebEndpoint(name = "ClusterVmWebServicePort")
    public ClusterVmWebService getClusterVmWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.standalone.example.org/", "ClusterVmWebServicePort"), ClusterVmWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLUSTERVMSERVICE_EXCEPTION!= null) {
            throw CLUSTERVMSERVICE_EXCEPTION;
        }
        return CLUSTERVMSERVICE_WSDL_LOCATION;
    }

}
